### ISSUE TITLE
Log-In STEM-app implementation in the MEapp on iOS

### ISSUE THREAD

**Issue by TomForus** [teamforus/concept-vote#1]
# Log-In STEM-app implementation in the MEapp on iOS

## Sort of Issue

Enhancement

## Prerequisites

1. Finish the native MEapp on iOS
2. Finish the native STEMapp on iOS

## Description

Create a Log-in possibility for the native iOS STEMapp in the native iOS MEapp.

## Functional Design (Enhancement)

1. STEMapp opens MEapp
2. STEMapp presents challenge
3. MEapp signs challenge
4. MEapp opens STEMapp
5. MEapp sends signed challenge

**User Story:** The user should have the possibility to log-in to the native iOS STEM-app via de native iOS ME-app.

**Comment by TomForus** [comment]
Jamal, this issue has been closed in the Concept-Identity repository. @jamalv /concept-identity#14

**Comment by jamalv** [comment]
closing the issue since prerequisite 2 is currently not planned
