### ISSUE TITLE
Log-In STEM-app implementation in the MEapp on Android

### ISSUE THREAD

**Issue by TomForus** [teamforus/concept-vote#2]
# Log-In STEM-app implementation in the MEapp on Android

## Sort of Issue

Enhancement

## Prerequisites

1. Finish the native MEapp on Android
2. Finish the native STEMapp on Android

## Description

Create a Log-in possibility for the native android STEMapp in the native android MEapp.

## Functional Design (Enhancement)

1. STEMapp opens MEapp
2. STEMapp presents challenge
3. MEapp signs challenge
4. MEapp opens STEMapp
5. MEapp sends signed challenge

**User Story:** The user should have the possibility to log-in to the native android STEM-app via de native Android ME-app.

**Comment by TomForus** [comment]
Issue moved from teamforus/concept-identity#13

**Comment by jamalv** [comment]
closing this issue since it is not currently relevant
